apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user
  name: user
spec:
  containers:
  - env:
    - name: JWT_KEY
      value: mysecretkey123
    - name: MONGO_URL
      value: mongodb://argadev:123456@user_db/?ssl=false
    image: user
    name: user
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
